// Drawer carries the dot-notation parts (Drawer.Root, ...)
// while every part stays available as a flat export below.
export { DrawerNamespace as Drawer } from './namespace'
export { default as DrawerRoot } from './Drawer.vue'
export { default as DrawerBackdrop } from './DrawerBackdrop.vue'
export { default as DrawerBody } from './DrawerBody.vue'
export { default as DrawerCloseTrigger } from './DrawerCloseTrigger.vue'
export { default as DrawerContent } from './DrawerContent.vue'
export { default as DrawerDialog } from './DrawerDialog.vue'
export { default as DrawerFooter } from './DrawerFooter.vue'
export { default as DrawerHandle } from './DrawerHandle.vue'
export { default as DrawerHeader } from './DrawerHeader.vue'
export { default as DrawerHeading } from './DrawerHeading.vue'
export { default as DrawerTrigger } from './DrawerTrigger.vue'
export * from './context'
