export { default as Tab } from './Tab.vue'
export { default as TabList } from './TabList.vue'
export { default as TabPanel } from './TabPanel.vue'
export { default as TabSeparator } from './TabSeparator.vue'
export { default as Tabs } from './Tabs.vue'
